name: Run Discord Bot

on:
  schedule:
    - cron: "0 */6 * * *" # запускается каждые 6 часов
  workflow_dispatch:      # можно вручную запускать

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Run Discord bot
      run: dotnet ./publish/publish/DiscordBot.dll
